### ISSUE TITLE
Unable to return msg

### ISSUE THREAD

**Issue by WolfwithSword** [eseunghwan/node-red-contrib-python-function-ps#1]
I'm running this in Node-Red in a docker container and I am unable to get any message sent out after the function.

NR Version:  2.2.3-12
Palette version: 0.0.11

~~~If I try to run the example flow I get the following error and nodered crashes:

7 Feb 17:55:38 - [error] Error: spawn /Users/shlee-d-1-nb/Desktop/node-red standalone/.node-red/env/bin/python ENOENT
    at Process.ChildProcess._handle.onexit (node:internal/child_process:283:19)
    at onErrorNT (node:internal/child_process:478:16)
    at processTicksAndRejections (node:internal/process/task_queues:83:21)
~~~
Fixed by changing the settings python path to "python3".

If I try my own custom script that works when run outside of this node, I get this and nodered still crashes:
```
7 Feb 17:57:04 - [error] SyntaxError: Unexpected token r in JSON at position 1
    at JSON.parse (<anonymous>)
    at PythonShell.asJson [as parser] (/data/node_modules/python-shell/index.js:377:21)
    at NewlineTransformer.<anonymous> (/data/node_modules/python-shell/index.js:142:43)
    at NewlineTransformer.emit (node:events:527:28)
    at addChunk (node:internal/streams/readable:315:12)
    at readableAddChunk (node:internal/streams/readable:289:9)
    at NewlineTransformer.Readable.push (node:internal/streams/readable:228:10)
    at Array.forEach (<anonymous>)
    at NewlineTransformer._transform (/data/node_modules/python-shell/index.js:63:15)
    at NewlineTransformer.Transform._write (node:internal/streams/transform:184:23)
```

This is whenever I return the msg with some payload that's generated and not hardcoded. I've ensured the datatype should be compatible.

**Comment by WolfwithSword** [comment]
Nevermind, data type was a string but being returned as a stream of data so it broke it. All good!
